<a href="https://colab.research.google.com/github/majaVtech/business-sales-analysis/blob/main/Notebooks/01_sales_analysisipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
url = ("https://raw.githubusercontent.com/majaVtech/business-sales-analysis/main/Data/raw_sales_data.csv")
df = pd.read_csv(url)

print("Shape:", df.shape)

Shape: (20050, 11)

In [3]:
df.head()

,order_id,order_date,customer_id,customer_name,product,category,quantity,unit_price,discount,city,payment_method
0,ORD17439,2025-01-01,CUST0044,Customer 0044,Coffee Maker,Home & Kitchen,3,93.21,0.00,Sarajevo,PayPal
1,ORD11153,2025-01-01,CUST0256,Customer 0256,Skincare Set,Beauty,5,40.14,0.15,Doboj,Cash on Delivery
2,ORD05185,2025-01-01,CUST0392,Customer 0392,Printer,Office Supplies,2,142.94,0.00,Mostar,Cash on Delivery
3,ORD00849,2025-01-01,CUST0369,Customer 0369,Coffee Maker,Home & Kitchen,4,92.24,0.00,Mostar,Cash on Delivery
4,ORD07394,2025-01-01,CUST0269,Customer 0269,Running Shoes,Sports,3,86.09,0.15,Banja Luka,Credit Card

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20050 entries, 0 to 20049
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        20050 non-null  object
 1   order_date      20050 non-null  object
 2   customer_id     20050 non-null  object
 3   customer_name   20050 non-null  object
 4   product         20050 non-null  object
 5   category        20050 non-null  object
 6   quantity        20050 non-null  int64
 7   unit_price      20050 non-null  float64
 8   discount        20050 non-null  float64
 9   city            19950 non-null  object
 10  payment_method  19974 non-null  object
dtypes: float64(2), int64(1), object(8)
memory usage: 1.7+ MB

In [6]:
df.isna().sum()

order_id            0
order_date          0
customer_id         0
customer_name       0
product             0
category            0
quantity            0
unit_price          0
discount            0
city              100
payment_method     76
dtype: int64

In [8]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 50

In [9]:
df.describe()

           quantity   unit_price      discount
count  20050.000000  20050.00000  20050.000000
mean       1.753367     91.33793      0.052581
std        1.030518     97.13023      0.059914
min       -1.000000    -50.00000      0.000000
25%        1.000000     30.32250      0.000000
50%        1.000000     73.15500      0.050000
75%        2.000000     93.95000      0.100000
max        5.000000    524.98000      0.200000

In [10]:
for column in ["product", "category", "city", "payment_method"]:
    print(f"\n--- {column} ---")
    print(df[column].value_counts(dropna=False))

--- product ---
product
Wireless Mouse         2976
Coffee Maker           2012
Mechanical Keyboard    1962
Air Fryer              1626
Office Chair           1591
Bluetooth Speaker      1576
Desk Lamp              1477
Notebook               1411
Running Shoes          1197
Yoga Mat               1009
Skincare Set            966
Smartphone              809
Printer                 808
Hair Dryer              630
Name: count, dtype: int64

--- category ---
category
Electronics        7291
Home & Kitchen     3621
Furniture          3048
Office Supplies    2204
Sports             2194
Beauty             1592
ELECTRONICS          32
FURNITURE            20
HOME & KITCHEN       17
OFFICE SUPPLIES      15
SPORTS               12
BEAUTY                4
Name: count, dtype: int64

--- city ---
city
Banja Luka    4484
Sarajevo      3837
Mostar        2450
Tuzla         2015
Zenica        1563
Bijeljina     1396
Prijedor      1224
Brcko         1170
Doboj         1057
Trebinje       754
NaN            100
Name: count, dtype: int64

--- payment_method ---
payment_method
Credit Card         8918
PayPal              4979
Cash on Delivery    3059
Bank Transfer       3018
NaN                   76
Name: count, dtype: int64